DROP DATABASE IF EXISTS employee_tracker;
CREATE DATABASE employee_tracker;
USE employee_tracker;

CREATE TABLE departments (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(50) NOT NULL
);

CREATE TABLE roles (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL
);

CREATE TABLE employees (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_title INTEGER NOT NULL,
  department INTEGER NOT NULL,
  salary INTEGER NOT NULL,
  manager VARCHAR(50) NOT NULL,
  CONSTRAINT fk_department FOREIGN KEY (department) REFERENCES departments(id) ON DELETE CASCADE,
  CONSTRAINT fk_role FOREIGN KEY (role_title) REFERENCES roles(id) ON DELETE CASCADE
);